=== WistfulHopes/GearLoader/schema/0.1.0/config.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://raw.githubusercontent.com/YouKnow232/GearLoader/refs/heads/main/schema/0.1.0/config.schema.json",
    "title": "Mod Config",
    "description": "Configuration settings for a GearLoader Mod",
    "type": "object",
    "properties": {
        "name": {
            "description": "Name of this mod",
            "type": "string"
        },
        "entryPoint": {
            "description": "Filename or relative path to mod entry point from this config file's path. If not given, the mod loader will grab the first dll found in this config file's folder.",
            "type": "string"
        },
        "version": {
            "description": "This mod's version",
            "type": "string"
        },
        "modLoaderVersion": {
            "description": "The version of GearLoader this mod was developed with. Specify this to ensure compatibility with future versions of GearLoader.",
            "type": "string"
        },
        "ignore": {
            "description": "If true, GearLoader will ignore this mod.",
            "type": "boolean"
        },
        "dependencies": {
            "description": "A list of other mods required by this mod",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "description": "Name of this dependency. This should match the name given to the mod loader by that mod's config.json",
                        "type": "string"
                    },
                    "version": {
                        "description": "A version qualifier for this dependency. Version constraints start with an optinal comparator followed by a semantic version string (e.g. \">=1.0.0\"). Comparators include '>=', '>', '=', '<', '<='. If none is specificed behavior defaults to \">=0.0.0\"",
                        "type": "string"
                    },
                    "optional": {
                        "description": "If `true` this mod will still load if the dependency is not installed, if `false` the mod loader will fail to load this mod if the dependency is not satisfied. Defaults to false.",
                        "type": "boolean"
                    }
                },
                "required": [ "name" ]
            }
        }
    },
    "required": [ "name" ]
}

=== WistfulHopes/GearLoader/examples/c_mod/config.json
{
    "$schema": "https://raw.githubusercontent.com/YouKnow232/GearLoader/refs/heads/mod-manager/schema/config.schema.json",
    "name": "example_c_mod",
    "version": "0.1.0",
    "modLoaderVersion": "0.1.0",
    "dependencies": [
        {
            "name": "baseMod"
        }
    ]
}

=== WistfulHopes/GearLoader/examples/cpp_mod/config.json
{
    "$schema": "https://raw.githubusercontent.com/YouKnow232/GearLoader/refs/heads/main/schema/0.1.0/config.schema.json",
    "name": "example_cpp_mod",
    "version": "0.1.0",
    "modLoaderVersion": "0.1.0",
    "dependencies": [
        {
            "name": "baseMod"
        }
    ]
}

=== WistfulHopes/GearLoader/test/modFolderTest/modB/config.json
{
    "$schema": "https://raw.githubusercontent.com/YouKnow232/GearLoader/refs/heads/main/schema/0.1.0/config.schema.json",
    "name": "modB",
    "entryPoint": "subdirectory/dummyModB.dll",
    "version": "0.1.1",
    "dependencies": [
        {
            "name": "modA"
        }
    ]
}

=== WistfulHopes/GearLoader/test/baseModTester/config.json
{
    "$schema": "https://raw.githubusercontent.com/YouKnow232/GearLoader/refs/heads/mod-manager/schema/0.1.0/config.schema.json",
    "name": "baseModTester",
    "version": "0.1.0",
    "modLoaderVersion": "0.1.0",
    "dependencies": [
        {
            "name": "baseMod",
            "version": "=0.1.0"
        }
    ]
}
